[package]
name = "budoux"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"

[dev-dependencies]
getopts = "0.2"
serde_json = "1.0"
